/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_bbcV4kd1J",
    "aws_user_pools_web_client_id": "33hluq880gk17tfghngoole71n",
    "oauth": {
        "domain": "exponent-dev001.auth.us-west-2.amazoncognito.com",
        "scope": [
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://applion.netlify.app/",
        "redirectSignOut": "https://applion.netlify.app/",
        "responseType": "code"
    }
};


export default awsmobile;
